name: bridges
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  path_provider: ^1.6.0
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: assets/img/icon.png
  adaptive_icon_background: "#3c3f65"
  adaptive_icon_foreground: assets/img/icon-adaptive.png

flutter_native_splash:
  image: assets/img/icon-adaptive.png
  color: "3c3f65"